[tool.black]
exclude = '^/(\.|dist|pybuild|venv)'

[tool.coverage.run]
omit = ["*/tests/*", "cumulusci/files/*"]
source = ["cumulusci"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "@abstract", "@abc.abstract"]

[tool.pytest.ini_options]
testpaths = "cumulusci"
addopts = "-p cumulusci.tests.pytest_plugins.pytest_typeguard -p cumulusci.tests.pytest_plugins.pytest_sf_vcr -p cumulusci.tests.pytest_plugins.pytest_sf_orgconnect"
markers = [
    "metadeploy: mark a test that interacts with the MetaDeploy REST API",
]
filterwarnings = [
    "error:ClassMovedWarning",
    "ignore::DeprecationWarning:.*.rflint",
    "ignore::DeprecationWarning:.*.selenium",
    "ignore::SyntaxWarning:.*.selenium",
]

[tool.isort]
profile = "black"
multi_line_output = 3
skip_glob = "cumulusci/**/__init__.py"
known_first_party = "cumulusci"
known_third_party = "robot"

[tool.pyright]
include = [
    'cumulusci/core/metadeploy/api.py',
    'cumulusci/tasks/metadata_etl/value_sets.py',
    'cumulusci/utils/deprecation.py',
    'cumulusci/salesforce_api/exceptions.py',
    'cumulusci/utils/salesforce/count_sobjects.py',
    'cumulusci/tasks/github/commit_status.py',
    'cumulusci/utils/xml/salesforce_encoding.py',
    'cumulusci/tasks/salesforce/UpdateAdminProfile.py',
    'cumulusci/salesforce_api/mc_soap_envelopes.py',
    'cumulusci/tasks/dx_convert_from.py',
    'cumulusci/salesforce_api/org_schema_models.py',
    'cumulusci/tasks/marketing_cloud/__init__.py',
    'cumulusci/tasks/github/pull_request.py',
    'cumulusci/robotframework/locators_56.py',
    'cumulusci/core/sfdx.py',
    'cumulusci/core/config/ScratchOrgConfig.py',
    'cumulusci/utils/waiting.py',
    'cumulusci/core/config/scratch_org_config.py',
    'cumulusci/tasks/metadata_etl/remote_site_settings.py',
    'cumulusci/tasks/salesforce/__init__.py',
    'cumulusci/tasks/marketing_cloud/get_user_info.py',
    'cumulusci/salesforce_api/__init__.py',
    'cumulusci/tasks/release_notes/__init__.py',
    'cumulusci/tasks/github/tag.py',
    'cumulusci/core/keychain/serialization.py',
    'cumulusci/core/dependencies/utils.py',
    'cumulusci/tasks/github/util.py',
    'cumulusci/tasks/salesforce/SOQLQuery.py',
    'cumulusci/core/runtime.py',
    'cumulusci/robotframework/locator_manager.py',
    'cumulusci/robotframework/pageobjects/__init__.py',
    'cumulusci/__main__.py',
    'cumulusci/core/metadeploy/__init__.py',
    'cumulusci/tasks/github/release_report.py',
    'cumulusci/utils/parallel/task_worker_queues/parallel_worker.py',
    'cumulusci/oauth/exceptions.py',
    'cumulusci/tasks/robotframework/__init__.py',
    'cumulusci/tasks/github/merge.py',
    'cumulusci/core/exceptions.py',
    'cumulusci/tasks/bulkdata/dates.py',
    'cumulusci/core/versions.py',
    'cumulusci/salesforce_api/soap_envelopes.py',
    'cumulusci/core/datasets.py',
    'cumulusci/core/template_utils.py',
    'cumulusci/utils/ziputils.py',
    'cumulusci/tasks/github/__init__.py',
    'cumulusci/tasks/metadata/__init__.py',
    'cumulusci/core/config/oauth2_service_config.py',
    'cumulusci/tasks/preflight/__init__.py',
    'cumulusci/tasks/vlocity/exceptions.py',
    'cumulusci/tasks/release_notes/parser.py',
    'cumulusci/__init__.py',
    'cumulusci/tasks/marketing_cloud/mc_constants.py',
    'cumulusci/utils/classutils.py',
    'cumulusci/core/keychain/environment_project_keychain.py',
    'cumulusci/tasks/salesforce/BaseSalesforceTask.py',
    'cumulusci/core/keychain/subprocess_keychain.py',
    'cumulusci/tasks/apex/__init__.py',
    'cumulusci/tasks/bulkdata/snowfakery_utils/subtask_configurator.py',
    'cumulusci/core/source/__init__.py',
    'cumulusci/tasks/bulkdata/generate.py',
    'cumulusci/core/debug.py',
    'cumulusci/tasks/salesforce/BaseRetrieveMetadata.py',
    'cumulusci/core/config/BaseTaskFlowConfig.py',
    'cumulusci/core/__init__.py',
    'cumulusci/utils/collections.py',
    'cumulusci/tasks/robotframework/lint.py',
    'cumulusci/salesforce_api/package_install.py',
    'cumulusci/tasks/bulkdata/generate_and_load_data_from_yaml.py',
    'cumulusci/core/config/BaseConfig.py',
    'cumulusci/core/source/local_folder.py',
    'cumulusci/core/source_transforms/__init__.py',
    'cumulusci/salesforce_api/filterable_objects.py',
    'cumulusci/cli/__init__.py',
    'cumulusci/core/config/base_task_flow_config.py',
    'cumulusci/tasks/bulkdata/snowfakery_utils/snowfakery_working_directory.py',
    'cumulusci/tasks/salesforce/license_preflights.py',
    'cumulusci/core/config/__init__.py',
    'cumulusci/tasks/metadata/ee_src.py',
    'cumulusci/tasks/salesforce/GetInstalledPackages.py',
    'cumulusci/tasks/__init__.py',
    'cumulusci/robotframework/locators_54.py',
    'cumulusci/tasks/salesforce/custom_settings.py',
    'cumulusci/core/dependencies/__init__.py',
    'cumulusci/utils/iterators.py',
    'cumulusci/core/config/OrgConfig.py',
    'cumulusci/robotframework/locators_55.py',
    'cumulusci/robotframework/pageobjects/PageObjectLibrary.py',
    'cumulusci/tasks/push/__init__.py',
    'cumulusci/oauth/__init__.py',
    'cumulusci/utils/http/requests_utils.py',
    'cumulusci/robotframework/__init__.py',
    'cumulusci/core/config/base_config.py',
    'cumulusci/tasks/metadata_etl/__init__.py',
    'cumulusci/tasks/robotframework/debugger/model.py',
    'cumulusci/utils/xml/robot_xml.py',
    'cumulusci/tasks/robotframework/debugger/__init__.py',
    'cumulusci/tasks/metadata_etl/permissions.py',
    'cumulusci/tasks/github/publish.py',
    'cumulusci/tasks/release_notes/exceptions.py',
    'cumulusci/tasks/bulkdata/generate_mapping_utils/mapping_generator_post_processes.py',
    'cumulusci/core/config/sfdx_org_config.py',
    'cumulusci/tasks/marketing_cloud/api.py',
    'cumulusci/tasks/bulkdata/__init__.py',
    'cumulusci/tasks/user/set_user_field.py',
    'cumulusci/tasks/metadata_etl/objects.py'
]
exclude = ["**/test_*", "**/tests/**"]
stubPath = ""
# Do not add to this list. Instead use
# # pyright: strict
strict = [
    'cumulusci/cli/__init__.py',
    'cumulusci/core/__init__.py',
    'cumulusci/core/debug.py',
    'cumulusci/core/dependencies/__init__.py',
    'cumulusci/core/keychain/environment_project_keychain.py',
    'cumulusci/core/keychain/serialization.py',
    'cumulusci/core/metadeploy/__init__.py',
    'cumulusci/core/source/__init__.py',
    'cumulusci/core/source_transforms/__init__.py',
    'cumulusci/core/versions.py',
    'cumulusci/oauth/__init__.py',
    'cumulusci/oauth/exceptions.py',
    'cumulusci/robotframework/locators_54.py',
    'cumulusci/robotframework/locators_55.py',
    'cumulusci/robotframework/locators_56.py',
    'cumulusci/salesforce_api/__init__.py',
    'cumulusci/salesforce_api/filterable_objects.py',
    'cumulusci/salesforce_api/mc_soap_envelopes.py',
    'cumulusci/salesforce_api/soap_envelopes.py',
    'cumulusci/tasks/__init__.py',
    'cumulusci/tasks/apex/__init__.py',
    'cumulusci/tasks/bulkdata/__init__.py',
    'cumulusci/tasks/bulkdata/generate.py',
    'cumulusci/tasks/github/__init__.py',
    'cumulusci/tasks/marketing_cloud/__init__.py',
    'cumulusci/tasks/marketing_cloud/mc_constants.py',
    'cumulusci/tasks/metadata/__init__.py',
    'cumulusci/tasks/metadata_etl/__init__.py',
    'cumulusci/tasks/preflight/__init__.py',
    'cumulusci/tasks/push/__init__.py',
    'cumulusci/tasks/release_notes/__init__.py',
    'cumulusci/tasks/release_notes/exceptions.py',
    'cumulusci/tasks/salesforce/BaseSalesforceTask.py',
    'cumulusci/tasks/vlocity/exceptions.py',
    'cumulusci/utils/soql.py'
]
